name: frosthaven_assistant
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.0+36

environment:
  sdk: ">=3.4.0 <3.6.0"
  #uncomment to peg flutter version to specific one.
  #flutter: '3.19.6'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  flutter_layout_grid: ^2.0.1
  reorderables: ^0.6.0
  search_choices: ^2.0.20
  built_collection: ^5.1.1 #for immutable lists

  flutter_animation_progress_bar:
    git:
      url: https://github.com/Tarmslitaren/Flutter-Animation-Progress-Bar

  animated_widgets: ^1.1.0 #for monster death animation
  dotted_border: ^2.0.0+2
  animated_text_kit: ^4.2.2
  network_info_plus: ^5.0.3
  dart_ipify: ^1.1.1 #get outgoing ip
  connectivity_plus: ^6.0.3 #poll for network changes
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.2.5 #keep awake on android
  window_manager: ^0.3.7 #to be able to set fullscreen on windows
  flutter_launcher_icons: ^0.13.1 #I can't believe we need a third party package to do icons..
  flutter_native_splash: ^2.2.8 # and same for splash :)
  url_launcher: ^6.2.1
  flutter_keyboard_visibility: ^6.0.0 #only way to check for keyboard closed event.
  responsive_framework: ^1.1.1
  override_text_scale_factor: ^1.0.2
  collection: ^1.18.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  format: ^1.4.0
  frosthaven_assistant_server:
    path: ../frosthaven_assistant_server



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  #test: ^1.25.8 # can use built in test version
  mockito: ^5.3.2
  build_runner: ^2.3.3
  fluent_assertions: ^0.4.0
  build_test: any
  json_diff: ^0.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48

flutter_native_splash:
  background_image: "assets/images/bg/frosthaven-bg.png"
  image: "assets/images/icon512x512.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/testData/
    - assets/testData/editions/
    - assets/testData/rooms/
    - assets/data/
    - assets/data/editions/
    - assets/data/rooms/
    - assets/images/abilities/ #for use with monster ability card
    - assets/images/attack/ #modifier deck
    - assets/images/loot/ #loot deck
    - assets/images/class-icons/
    - assets/images/monsters/ #portraits
    - assets/images/summon/
    - assets/images/psd/
    - assets/images/bg/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #- family: Nyala
     # fonts:
      #  - asset: assets/fonts/nyala.ttf
    #         style: italic
    - family: Majalla
      fonts:
        - asset: assets/fonts/majallab.ttf
          weight: 400 #does nothing
    - family: Pirata
      fonts:
        - asset: assets/fonts/PirataOne-Gloomhaven.ttf
    - family: GermaniaOne
      fonts:
        - asset: assets/fonts/GermaniaOne-Regular.ttf
    - family: Markazi
      fonts:
        - asset: assets/fonts/MarkaziText-VariableFont_wght.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

